### ISSUE TITLE
Ausblick

### ISSUE THREAD

**Issue by joachimprinzbach** [baloise/talk-cicd-javascript#9]
- Containerisierung
- Open Shift
- ChatOps

**Comment by joachimprinzbach** [comment]
- learnings from JS applied back to Java -> Multi branch SNAPSHOT versioning

**Comment by schlijo** [comment]
- security and license checks for npm packages -> IQ Server
 - maven installed on ci -> fetch temporary via artifact repository
 - need for maven or gradle to define and download nodejs version
 - nodejs docker img?
